force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Trailhead Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/ActiveEvent__c.field-meta.xml
<CustomField>
    <fullName>ActiveEvent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/Event_X_Action__c.object-meta.xml
<CustomObject>
    <label>Event By Action</label>
    <nameField>
        <displayFormat>ExA-{0000}</displayFormat>
        <label>Event X Action Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events By Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_X_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Actions By Events</relationshipLabel>
    <relationshipName>Actions_X_Events</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/fields/ActiveEvent__c.field-meta.xml
<CustomField>
    <fullName>ActiveEvent__c</fullName>
    <formula>Event__r.ActiveEvent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events By Actions</relationshipLabel>
    <relationshipName>Events_X_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ActionCreate.cls
public with sharing class ActionCreate extends ETLC_ApexBridge_Abstract {
    public override void process(ETLC_ApexBridge_Request request, ETLC_ApexBridge_Response response) {
        if (request.method == 'getAllEvents') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getAllEvents(request));
        } else if (request.method == 'getSelectedEvents') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getSelectedEvents(request));
        } else {
            throw new ETLC_Exception('Unexpected "method" received');
        }
    }

    private List<Event__c> getAllEvents(ETLC_ApexBridge_Request request) {
        List<Event__c> events = [
            SELECT Id, Name, ActiveEvent__c 
            FROM Event__c 
            WHERE ActiveEvent__c = true 
            ORDER BY Name 
        ];
        ETLC_SecuredDB.validateQuery(events);
        return events;
    }

    private List<Id> getSelectedEvents(ETLC_ApexBridge_Request request) {
        String actionId = String.valueOf(request.getInputValue('actionId'));
        
        List<Id> output = new List<Id>();
        List<Event__c> events = [
            SELECT Id, Name, ActiveEvent__c 
            FROM Event__c
            WHERE Id IN (SELECT Event__c FROM Event_X_Action__c WHERE Action__c = :actionId)
        ];
        ETLC_SecuredDB.validateQuery(events);
        for (Event__c event : events) {
            output.add(event.Id);
        }
        return output;
    }

    private void updateEventActions(ETLC_ApexBridge_Request request) {
        String actionId = String.valueOf(request.getInputValue('actionId'));
        List<Id> events = (List<ID>) request.getInputValue('events');


    }
}