force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/AppName__c.field-meta.xml
<CustomField>
    <fullName>AppName__c</fullName>
    <label>App Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Command__c.field-meta.xml
<CustomField>
    <fullName>Command__c</fullName>
    <label>Command</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Expected__c.field-meta.xml
<CustomField>
    <fullName>Expected__c</fullName>
    <label>Expected</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Ext Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Action__c/fields/Fix__c.field-meta.xml
<CustomField>
    <fullName>Fix__c</fullName>
    <label>Fix</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Check Contains</fullName>
            </value>
            <value>
                <fullName>Check Exact</fullName>
            </value>
            <value>
                <fullName>Check Path</fullName>
            </value>
            <value>
                <fullName>Execute</fullName>
            </value>
            <value>
                <fullName>Execute Async</fullName>
            </value>
            <value>
                <fullName>Bookmark</fullName>
            </value>
            <value>
                <fullName>JSON File - Check</fullName>
            </value>
            <value>
                <fullName>JSON File - Edit</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Open Application</fullName>
            </value>
            <value>
                <fullName>Write</fullName>
            </value>
            <value>
                <fullName>Include Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Trailhead Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/Event_X_Action__c.object-meta.xml
<CustomObject>
    <label>Event By Action</label>
    <nameField>
        <displayFormat>ExA-{0000}</displayFormat>
        <label>Event X Action Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events By Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_X_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Actions By Events</relationshipLabel>
    <relationshipName>Actions_X_Events</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events By Actions</relationshipLabel>
    <relationshipName>Events_X_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JSON_Action__c/JSON_Action__c.object-meta.xml
<CustomObject>
    <label>JSON Action</label>
    <nameField>
        <displayFormat>JSON-{0000}</displayFormat>
        <label>JSON Action Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JSON Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JSON_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>JSON Actions</relationshipLabel>
    <relationshipName>JSON_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JSON_Action__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Action__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ActionsView.cls
public with sharing class ActionsView extends ETLC_ApexBridge_Abstract {
    public override void process(ETLC_ApexBridge_Request request, ETLC_ApexBridge_Response response) {
        if (request.method == 'getEvents') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getEvents(request));
        } else if (request.method == 'getActions') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getActions(request));
        } else if (request.method == 'updateAction') {
            updateAction(request);
            response.output = null;
        } else {
            throw new ETLC_Exception('Unexpected "method" received');
        }
    }

    private List<Event__c> getEvents(ETLC_ApexBridge_Request request) {
        List<Event__c> events = [
            SELECT Id, Name, Active__c 
            FROM Event__c 
            WHERE Active__c = true 
            ORDER BY Name 
        ];
        ETLC_SecuredDB.validateQuery(events);
        return events;
    }

    private List<Action__c> getActions(ETLC_ApexBridge_Request request) {
        String eventId = String.valueOf(request.getInputValue('eventId'));
        List<Action__c> actions = [
            SELECT ID, Name, AppName__c, Command__c, Enabled__c, ErrorMessage__c, Fix__c, Expected__c, 
            Message__c, Operation__c, Order__c, ExtId__c, 
            (SELECT Id, Name, Event__c, Event__r.Name FROM Actions_X_Events__r),
            (SELECT Id, Name, Action__c, Key__c, Path__c, Value__c FROM JSON_Actions__r)
            FROM Action__c 
            WHERE ID IN (SELECT Action__c FROM Event_X_Action__c WHERE Event__c = :eventId)
            ORDER BY Order__c ASC
        ];
        ETLC_SecuredDB.validateQuery(actions);
        return actions;
    }

    private void updateAction(ETLC_ApexBridge_Request request) {
        List<Action__c> actions = request.records;
        ETLC_SecuredDB.performDML(ETLC_SecuredDB.Operation.Updating, actions); 
    }
}