force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Trailhead Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/ActiveEvent__c.field-meta.xml
<CustomField>
    <fullName>ActiveEvent__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/Event_X_Action__c.object-meta.xml
<CustomObject>
    <label>Event By Action</label>
    <nameField>
        <displayFormat>ExA-{0000}</displayFormat>
        <label>Event X Action Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events By Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_X_Action__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Actions By Events</relationshipLabel>
    <relationshipName>Actions_X_Events</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/fields/ActiveEvent__c.field-meta.xml
<CustomField>
    <fullName>ActiveEvent__c</fullName>
    <formula>Event__r.ActiveEvent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events By Actions</relationshipLabel>
    <relationshipName>Events_X_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_X_Action__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <defaultValue>&#39;NO_ID_YET&#39;</defaultValue>
    <description>18 + | + 18 = 37</description>
    <label>Unique Key</label>
    <length>37</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Data.cls
public with sharing class Data extends ETLC_ApexBridge_Abstract {
    public override void process(ETLC_ApexBridge_Request request, ETLC_ApexBridge_Response response) {
        if (request.method == 'getAllEvents') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getAllEvents(request));
        } else if (request.method == 'getSelectedEvents') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getSelectedEvents(request));
        } else if (request.method == 'getActionsByEvent') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getActionsByEvent(request));
        } else if (request.method == 'getEventsByAction') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getEventsByAction(request));
        } else if (request.method == 'getEventsByAllActions') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(getEventsByAllActions(request));
        } else if (request.method == 'updateActions') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(updateActions(request));
        } else if (request.method == 'updateEventsByAction') {
            response.output = ETLC_ApexBridge_Abstract.encodeData(updateEventsByAction(request));
        } else {
            throw new ETLC_Exception('Unexpected "method" received');
        }
    }
    
    
    private List<Event__c> getAllEvents(ETLC_ApexBridge_Request request) {
        List<Event__c> events = [
            SELECT Id, Name, ActiveEvent__c 
            FROM Event__c 
            WHERE ActiveEvent__c = true 
            ORDER BY Name 
        ];
        ETLC_SecuredDB.validateQuery(events);
        return events;
    }
    private List<Id> getSelectedEvents(ETLC_ApexBridge_Request request) {
        String actionId = String.valueOf(request.getInputValue('actionId'));
        
        List<Id> output = new List<Id>();
        List<Event__c> events = [
            SELECT Id, Name, ActiveEvent__c 
            FROM Event__c
            WHERE Id IN (SELECT Event__c FROM Event_X_Action__c WHERE Action__c = :actionId)
        ];
        ETLC_SecuredDB.validateQuery(events);
        for (Event__c event : events) {
            output.add(event.Id);
        }
        return output;
    }
    private List<Action__c> getActionsByEvent(ETLC_ApexBridge_Request request) {
        String eventId = String.valueOf(request.getInputValue('eventId'));
        List<Action__c> actions = [SELECT ID, Order__c FROM Action__c
                                   WHERE ID IN (SELECT Action__c 
                                                FROM Event_X_Action__c
                                                WHERE Event__c = :eventId)
                                   ORDER BY Order__c ASC];
        ETLC_SecuredDB.validateQuery(actions);
        return actions;
    }
    private List<Event__c> getEventsByAction(ETLC_ApexBridge_Request request) {
        String actionId = String.valueOf(request.getInputValue('actionId'));
        List<Event__c> actions = [SELECT ID FROM Event__c
                                  WHERE ID IN (SELECT Event__c 
                                               FROM Event_X_Action__c
                                               WHERE Action__c = :actionId)
                                  ORDER BY Name ASC];
        ETLC_SecuredDB.validateQuery(actions);
        return actions;
    }
    private Map<Id, List<Id>> getEventsByAllActions(ETLC_ApexBridge_Request request) {
        Map<Id, List<Id>> output = new Map<Id, List<Id>>();
        List<Action__c> actions = [SELECT Id, (SELECT Event__c FROM Actions_X_Events__r) FROM Action__c];
        ETLC_SecuredDB.validateQuery(actions);
        for (Action__c action : actions) {
            List<Id> eventIds = new List<Id>();
            for (Event_X_Action__c eXa : action.Actions_X_Events__r) {
                eventIds.add(eXa.Event__c);
            }
            output.put(action.Id, eventIds);
        }
        return output;
    }
    private List<Event_X_Action__c> updateEventsByAction(ETLC_ApexBridge_Request request) {
        List<Event_X_Action__c> eXas;
        String actionId = String.valueOf(request.getInputValue('actionId'));
        List<Object> eventIds = (List<Object>) request.getInputValue('eventIds');
        
        // Delete the old records
        eXas = [SELECT ID FROM Event_X_Action__c WHERE Action__c = :actionId];
        ETLC_SecuredDB.performDML(ETLC_SecuredDB.Operation.Deleting, eXas);
        
        // Create the new records
        eXas = new List<Event_X_Action__c>();
        for (Object objEventId : eventIds) {
            String strEventId = String.valueOf(objEventId);
            eXas.add(new Event_X_Action__c(
                Action__c = actionId,
                Event__c = strEventId,
                UniqueKey__c = actionId + '-' + strEventId
            ));
        }
        ETLC_SecuredDB.performDML(ETLC_SecuredDB.Operation.Inserting, eXas);
        return eXas;
    }
    private List<Action__c> updateActions(ETLC_ApexBridge_Request request) {
        List<Action__c> actions = request.records;
        // ETLC_SecuredDB.performDML(ETLC_SecuredDB.Operation.Updating, actions);
        update actions;
        return getActionsByEvent(request);
    }
}